openapi: "3.1.0"
info:
  title: "spring_gift API"
  description: "spring_gift API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
paths:
  /api/products:
    get:
      summary: "GET api/products"
      operationId: "getPage"
      parameters:
        - name: "page"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: "0"
        - name: "size"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int32"
            default: "10"
        - name: "sort"
          in: "query"
          required: false
          schema:
            type: "array"
            items:
              type: "string"
            default: "id"
        - name: "categoryId"
          in: "query"
          required: false
          schema:
            type: "integer"
            format: "int64"
            default: "0"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/ProductResponse"
    post:
      summary: "POST api/products"
      operationId: "add"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProductResponse"
  /api/products/{id}:
    get:
      summary: "GET api/products/{id}"
      operationId: "get"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ProductResponse"
    put:
      summary: "PUT api/products/{id}"
      operationId: "update"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Void"
    delete:
      summary: "DELETE api/products/{id}"
      operationId: "delete"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Void"
components:
  schemas:
    ProductResponse:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        price:
          type: "integer"
          format: "int32"
        imageUrl:
          type: "string"
        categoryName:
          type: "String"
    GiftOptionRequest:
      type: "object"
      properties:
        name:
          type: "string"
        quantity:
          type: "integer"
          format: "int32"
    ProductRequest:
      type: "object"
      properties:
        name:
          type: "string"
          default: "test1"
        price:
          type: "integer"
          format: "int32"
          default: "100"
        imageUrl:
          type: "string"
          default: "http/image"
        categoryId:
          type: "integer"
          format: "int64"
          default: "1"
        giftOptions:
          type: "array"
          items:
            $ref: "#/components/schemas/GiftOptionRequest"
    Void:
      type: "object"
      properties: { }