openapi: "3.1.0"
info:
  title: "spring_gift API"
  description: "spring_gift API"
  version: "1.0.0"
servers:
  - url: "http://localhost:8080"
paths:
  /api/categories:
    get:
      summary: "GET api/categories"
      operationId: "getCategories"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/CategoryResponse"
    post:
      summary: "POST api/categories"
      operationId: "add"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CategoryRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CategoryResponse"
  /api/categories/{id}:
    put:
      summary: "PUT api/categories/{id}"
      operationId: "update"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CategoryRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/CategoryResponse"
    delete:
      summary: "DELETE api/categories/{id}"
      operationId: "delete"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int32"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Void"
components:
  schemas:
    CategoryResponse:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        color:
          type: "string"
        imageUrl:
          type: "string"
        description:
          type: "string"
    CategoryRequest:
      type: "object"
      properties:
        name:
          type: "string"
          default: "catetest1"
        color:
          type: "string"
          default: "red"
        description:
          type: "string"
          default: "카테고리임."
        imageUrl:
          type: "string"
          default: "http://localhoss.com"
    Void:
      type: "object"
      properties: { }